spring:
  datasource:
    url: jdbc:h2:mem:my_ouath2_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
