spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0
      client:
        provider:
          azure-ad:
            issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0
        registration:
          azure-ad:
            provider: azure-ad
            client-id:
            client-secret:
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
            #            redirect-uri: http://localhost:8080${spring.webflux.base-path}/login/oauth2/code/azure-ad
#            redirect-uri: http://localhost:4200/#/dashboard
  threads:
    virtual:
      enabled: true

logging:
  level:
    org.springframework.security.oauth2: debug
