spring:
  datasource:
    url: jdbc:postgres://localhost:5431/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        provider:
          azuread:
            issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0
        registration:
          azuread:
            provider: azuread
            client-id:
            client-secret:
            scope: openid, profile, email, offline_access
            redirect-uri: http://localhost:4200/login/oauth2/code/azuread
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0
  threads:
    virtual:
      enabled: true
#logging:
#  level:
#    org.springframework.security: debug
