spring:
  datasource:
    url: jdbc:h2:mem:my_oauth2_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        provider:
          azuread:
            issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0
        registration:
          azuread:
            provider: azuread
            client-id: 9e8e2c62-2fd4-4d3d-9d9e-9ac43cd9e485
            client-secret: UN58Q~ztUZ4.9RffCuMzYd.3DK5jFNChtYd2Tb_a
            scope: openid, profile, email, offline_access
            redirect-uri: http://localhost:4200/login/oauth2/code/azuread
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0
logging:
  level:
    org.springframework.security: debug
