spring:
  datasource:
    url: jdbc:h2:mem:my_ouath2_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/{tenantId}/v2.0
        registration:
          azure:
            provider: azure
            client-id: '***'      # Application (client) ID
            client-secret: '***'  # Client secret - For-Angular-UI
            scope: openid, profile, email, offline_access
            redirect-uri: http://localhost:4200/login/oauth2/code/azuread
