spring:
  datasource:
    url: jdbc:postgres://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0
  threads:
    virtual:
      enabled: true
  cloud:
    azure:
      active-directory:
        profile:
          tenant-id: 1b286c40-c2fd-46d5-a553-b6502b89f42d
        credential:
          client-secret:
          client-id:
        enabled: true
#logging:
#  level:
#    org.springframework.security: debug
