DROP TABLE IF EXISTS OAUTH_USER;
DROP TABLE IF EXISTS OAUTH_ROLE;

CREATE TABLE OAUTH_USER
(
    ID       BIGINT       NOT NULL AUTO_INCREMENT,
    NAME     VARCHAR(255) NOT NULL,
    EMAIL    VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE OAUTH_ROLE
(
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    ROLE       VARCHAR(255) NOT NULL,
    OAUTH_USER BIGINT       NOT NULL REFERENCES OAUTH_USER (ID),
    PRIMARY KEY (ID)
);
